### ISSUE TITLE
Location for manual please?

### ISSUE THREAD

**Issue by complexgenome** [kjgleason/primo#3]
Is there a manual for this package?

Also, is this package submitted to bioconductor or CRAN? I can't in any repository, sorry.

**Comment by kjgleason** [comment]
Hi, sariya. Thanks for your interest in the package! The functions should each have manuals (e.g. in ../man) that should also be able to be accessed via ?() once you've installed the package. There is also a tutorial in the form of a vignette (../vignettes). Let me know if you are still unable to access the manual(s) you need.

The package has not yet been submitted to CRAN or bioconductor.

**Comment by complexgenome** [comment]
Sorry, I'm struggling for I've never used vignette within a package.

`vignette(package="Primo") `
It gives an error. 

I navigate to the library location. 
```
setwd("/home/user/libraries_R/R_LIB4.0/Primo")
vignette (../vignettes)
Error in vignette(../vignettes) : object '..' not found
vignette (vignettes)
Error in vignette(vignettes) : object 'vignettes' not found

```
I'm lost for this is absolutely counter intuitive.

Also, I think going through each function from man would be really difficult. 

Thanks for your prompt reply. :)

**Comment by kjgleason** [comment]
Can you confirm that you [set the option to build the vignette](https://github.com/r-lib/devtools/issues/1896) when installing the package through `devtools::install_github()`? I believe the default does not build the vignette. If you changed the option and it's still not rendering then please let me know so that I can further troubleshoot.

**Comment by kjgleason** [comment]
Closing due to one year passing since last response.
